"""Canonical financial KPI metadata independent of benchmark ground truth."""

from __future__ import annotations

KPI_DESCRIPTIONS: dict[str, str] = {
    "revenue": "Total operating revenue / net sales (top line). Flow. Reporting currency.",
    "cost_of_revenue": "Cost of goods and services sold. Flow. Reporting currency.",
    "gross_profit": "Revenue minus cost of revenue. Flow. Reporting currency.",
    "rd_expense": "Research and development expense (R&D only — exclude SG&A). Flow. Reporting currency.",
    "sga_expense": "Selling, general and administrative expense; when no combined SG&A row exists, LEDGER accepts general and administrative expense as its tag-waterfall fallback. Flow. Reporting currency.",
    "operating_income": "Operating income / operating profit (EBIT-level). Flow. Reporting currency. Sign: usually positive but can be negative.",
    "interest_expense": "Interest expense on debt. Flow. Reporting currency. Sign: positive cost.",
    "income_tax_expense": "Income tax expense / benefit. Flow. Reporting currency. Sign: positive expense, negative benefit.",
    "net_income": "Net income attributable to parent / common shareholders only; exclude non-controlling interest. Flow. Reporting currency.",
    "eps_basic": "Basic earnings per share. Per-share. Reporting currency / share.",
    "eps_diluted": "Diluted earnings per share. Per-share. Reporting currency / share.",
    "total_assets": "Total assets at period end. Stock. Reporting currency.",
    "total_liabilities": "Total liabilities at period end. Stock. Reporting currency.",
    "stockholders_equity": "Total stockholders' / shareholders' equity attributable to parent only, excluding non-controlling interest. Stock. Reporting currency.",
    "stockholders_equity_incl_nci": "Total equity including non-controlling / minority interest. Stock. Reporting currency.",
    "cash_and_equivalents": "Cash and cash equivalents, unrestricted only; exclude restricted cash. Stock. Reporting currency.",
    "cash_incl_restricted": "Cash, cash equivalents and restricted cash combined. Stock. Reporting currency.",
    "long_term_debt_total": "Printed total long-term-debt balance used by LEDGER, excluding a separately reported current portion. Stock. Reporting currency.",
    "long_term_debt_noncurrent": "Long-term debt excluding the current portion. Stock. Reporting currency.",
    "long_term_debt_current": "Current portion of long-term debt only. Stock. Reporting currency.",
    "short_term_borrowings": "Short-term borrowings with original maturity of one year or less. Stock. Reporting currency.",
    "inventory": "Inventory, net. Stock. Reporting currency.",
    "accounts_receivable": "Accounts receivable, current and net of allowance. Stock. Reporting currency.",
    "accounts_payable": "Accounts payable, current. Stock. Reporting currency.",
    "shares_outstanding": "Common shares outstanding at period end. Unit: shares, not currency; emit the raw share count.",
    "operating_cash_flow": "Net cash provided by / used in operating activities. Flow. Reporting currency; keep the reported sign.",
    "investing_cash_flow": "Net cash provided by / used in investing activities. Flow. Reporting currency; keep the reported sign.",
    "financing_cash_flow": "Net cash provided by / used in financing activities. Flow. Reporting currency; keep the reported sign.",
    "capex": "Capital expenditure: payments to acquire property, plant and equipment. Flow. Reporting currency. Sign: positive cash outflow.",
    "depreciation_amortization": "Depreciation, depletion and amortization addback; LEDGER falls back to depreciation when no combined row exists. Flow. Reporting currency. Sign: positive.",
    "dividends_paid": "Cash dividends paid to common shareholders during the period. Flow. Reporting currency. Sign: positive cash outflow.",
}

KPI_KEYS = tuple(KPI_DESCRIPTIONS)


KPI_ALIASES: dict[str, tuple[str, ...]] = {
    "revenue": (
        "revenue",
        "revenues",
        "net revenue",
        "total net revenue",
        "net sales",
        "sales",
    ),
    "cost_of_revenue": (
        "cost of revenue",
        "cost of revenues",
        "cost of sales",
        "cost of goods sold",
    ),
    "gross_profit": ("gross profit", "gross margin"),
    "rd_expense": ("research and development", "r&d"),
    "sga_expense": (
        "selling general and administrative",
        "general and administrative",
        "general & administrative",
        "sg&a",
    ),
    "operating_income": ("operating income", "operating profit", "income from operations"),
    "interest_expense": ("interest expense", "finance costs", "finance expense"),
    "income_tax_expense": (
        "income tax expense",
        "income tax benefit",
        "provision for income taxes",
    ),
    "net_income": (
        "net income attributable",
        "net income",
        "net loss",
        "net earnings",
        "profit attributable",
        "profit for the year",
    ),
    "eps_basic": (
        "basic earnings per share",
        "basic eps",
        "loss per share",
        "basic and diluted",
    ),
    "eps_diluted": (
        "diluted earnings per share",
        "diluted eps",
        "loss per share",
        "basic and diluted",
    ),
    "total_assets": ("total assets",),
    "total_liabilities": ("total liabilities",),
    "stockholders_equity": (
        "stockholders equity",
        "shareholders equity",
        "equity attributable to owners",
    ),
    "stockholders_equity_incl_nci": (
        "total equity",
        "equity including noncontrolling",
        "equity attributable to owners and non-controlling interests",
    ),
    "cash_and_equivalents": ("cash and cash equivalents",),
    "cash_incl_restricted": ("cash cash equivalents and restricted cash",),
    "long_term_debt_total": (
        "total long term debt",
        "long term debt",
        "long term debt less current portion",
        "debt obligations",
        "notes payable and obligations under capital leases",
    ),
    "long_term_debt_noncurrent": ("long term debt", "noncurrent debt"),
    "long_term_debt_current": (
        "current portion of long term debt",
        "current maturities of long term debt",
        "current maturities of notes payable",
        "current notes payable",
        "note payable current portion",
        "less current portion of notes payable",
        "current debt",
    ),
    "short_term_borrowings": (
        "short term borrowings",
        "short term debt",
        "current debt",
        "bank loans",
        "bank borrowings",
        "current maturities of notes payable",
        "current maturities of long term debt",
        "current portion of long term debt",
        "repurchase agreements",
        "line of credit",
        "commercial paper",
    ),
    "inventory": ("inventory", "inventories"),
    "accounts_receivable": (
        "accounts receivable",
        "trade receivables",
        "trade and other receivables",
        "interest receivable",
        "accounts and notes receivable",
    ),
    "accounts_payable": (
        "accounts payable",
        "trade payables",
        "trade and other payables",
        "accounts payable and other liabilities",
        "accounts payable and accrued liabilities",
    ),
    "shares_outstanding": (
        "shares outstanding",
        "common shares outstanding",
        "ordinary shares outstanding",
        "issued and fully paid",
    ),
    "operating_cash_flow": (
        "net cash provided by operating activities",
        "net cash used in operating activities",
        "net cash from operating activities",
        "operating cash flow",
    ),
    "investing_cash_flow": (
        "net cash provided by investing activities",
        "net cash used in investing activities",
        "net cash from investing activities",
        "investing cash flow",
    ),
    "financing_cash_flow": (
        "net cash provided by financing activities",
        "net cash used in financing activities",
        "net cash from financing activities",
        "financing cash flow",
    ),
    "capex": (
        "capital expenditures",
        "purchases of property plant and equipment",
        "payments for property plant and equipment",
        "investments in property plant and equipment",
        "purchase of ppe",
    ),
    "depreciation_amortization": (
        "depreciation and amortization",
        "depreciation and amortisation",
        "depreciation depletion and amortization",
        "depreciation, depletion and amortization",
        "depreciation amortization",
        "depreciation",
    ),
    "dividends_paid": (
        "dividends paid",
        "payment of dividends",
        "dividends paid to shareholders",
    ),
}


PER_SHARE_KPIS = {"eps_basic", "eps_diluted"}
SHARE_COUNT_KPIS = {"shares_outstanding"}
POSITIVE_OUTFLOW_KPIS = {"capex", "dividends_paid"}
POSITIVE_MAGNITUDE_KPIS = POSITIVE_OUTFLOW_KPIS | {
    "cost_of_revenue",
    "interest_expense",
    "sga_expense",
    "total_liabilities",
    "long_term_debt_total",
    "long_term_debt_noncurrent",
    "long_term_debt_current",
    "short_term_borrowings",
}
